name: gglb-dev-push
on:
  push:
    paths:
      - gin-gorm-logrus-basic/**
    branches:
      - main
      - develop
      - feature/*
      - fix/*
      - refactor/*

defaults:
  run:
    working-directory: gin-gorm-logrus-basic

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Go Setup
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
      - name: Go Cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

  lint:
    name: Make CI Lint
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.36
          working-directory: gin-gorm-logrus-basic
          args: -c ./configs/.golangci.yml

  test:
    name: Make Go Test
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Test
        run: make go-test

  notify:
    name: Slack Notification
    needs:
      - lint
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_GITHUB }}
          SLACK_USERNAME: ${{ github.repository }}
          SLACK_ICON: https://emoji.slack-edge.com/T01LG4HBVK5/gopher/64c6a6d67d85c69c.png
