name: gglb-dev-push
on:
  push:
    paths:
      - gin-gorm-logrus-basic/**
    branches:
      - main
      - develop
      - feature/*
      - fix/*
      - refactor/*

defaults:
  run:
    working-directory: gin-gorm-logrus-basic

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Go Setup
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
      - name: Go Cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

  lint:
    name: Make CI Lint
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: check directory
        run: pwd && ls -a
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.36
          args: -c ${{ github.workspace }}/configs/.golangci.yml

  test:
    name: Make Go Test
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Test
        run: make go-test

#    name: Lint and Test
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout Code
#        uses: actions/checkout@v2
#      - name: Go Setup
#        uses: actions/setup-go@v2
#        with:
#          go-version: ^1.15
#      - name: Go Cache
#        uses: actions/cache@v2
#        with:
#          path: ~/go/pkg/mod
#          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
#          restore-keys: ${{ runner.os }}-go-
#      - name: Make CI Lint
#        run: make ci-lint
#      - name: Make Go Test
#        run: make go-test